<?php
$page_title = 'Home';
require_once 'includes/header.php';
?>

<!-- Hero Section -->
<section class="hero">
    <div class="container">
        <div class="hero-content">
            <h1>Master Your Technical Interviews</h1>
            <p>Comprehensive preparation platform with expert guidance, real-world practice, and proven strategies to land your dream job at top tech companies.</p>
            <div class="hero-buttons">
                <a href="courses.php" class="btn btn-primary">Explore Courses</a>
                <a href="mocks.php" class="btn btn-outline">Try Mock Interview</a>
            </div>
        </div>
    </div>
</section>

<!-- Technology Carousel Section -->
<section class="section carousel-section">
    <div class="container">
        <div class="section-title">
            <h2>Master In-Demand Technologies</h2>
            <p>Learn the most sought-after programming languages and technologies that top companies are looking for</p>
        </div>
        <div class="carousel-container" id="tech-carousel">
            <!-- Carousel content will be generated by JavaScript -->
        </div>
    </div>
</section>

<!-- About Company Section -->
<section class="section">
    <div class="container">
        <div class="about-company">
            <div class="about-content animate-fade-in-left">
                <h2>About InterviewPrep</h2>
                <p>We are a leading interview preparation platform dedicated to helping aspiring developers and engineers succeed in their technical interviews. With over 5 years of experience and a team of industry experts from top tech companies, we provide comprehensive training that bridges the gap between academic knowledge and industry requirements.</p>
                <p>Our proven methodology has helped thousands of students land positions at prestigious companies like Google, Amazon, Microsoft, and many more. We combine theoretical knowledge with practical application, ensuring our students are well-prepared for any technical challenge.</p>
                <p>Join our community of successful professionals and take the next step in your career journey with confidence and expertise.</p>
                <a href="about.php" class="btn btn-primary">Learn More About Us</a>
            </div>
            <div class="about-images animate-fade-in-right">
                <div class="about-image">
                    <div style="height: 200px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); display: flex; align-items: center; justify-content: center; color: white; font-size: 3rem;">
                        <i class="fas fa-users"></i>
                    </div>
                </div>
                <div class="about-image">
                    <div style="height: 200px; background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); display: flex; align-items: center; justify-content: center; color: white; font-size: 3rem;">
                        <i class="fas fa-laptop-code"></i>
                    </div>
                </div>
                <div class="about-image">
                    <div style="height: 200px; background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); display: flex; align-items: center; justify-content: center; color: white; font-size: 3rem;">
                        <i class="fas fa-trophy"></i>
                    </div>
                </div>
                <div class="about-image">
                    <div style="height: 200px; background: linear-gradient(135deg, #43e97b 0%, #38f9d7 100%); display: flex; align-items: center; justify-content: center; color: white; font-size: 3rem;">
                        <i class="fas fa-rocket"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Students Work At Section -->
<section class="section bg-secondary">
    <div class="container">
        <div class="section-title">
            <h2>Our Students Work At</h2>
            <p>Join thousands of successful professionals who have landed their dream jobs at top companies</p>
        </div>
        <div class="companies-grid">
            <div class="company-card">
                <div class="company-logo" style="background: white; padding: 1rem;">
                    <svg width="60" height="20" viewBox="0 0 272 92" xmlns="http://www.w3.org/2000/svg">
                        <g fill="none" fill-rule="evenodd">
                            <path d="M115.75 47.18c0 12.77-9.99 22.18-22.25 22.18s-22.25-9.41-22.25-22.18C71.25 34.32 81.24 25 93.5 25s22.25 9.32 22.25 22.18zm-9.74 0c0-7.98-5.79-13.44-12.51-13.44S80.99 39.2 80.99 47.18c0 7.9 5.79 13.44 12.51 13.44s12.51-5.55 12.51-13.44z" fill="#EA4335"/>
                            <path d="M163.75 47.18c0 12.77-9.99 22.18-22.25 22.18s-22.25-9.41-22.25-22.18c0-12.85 9.99-22.18 22.25-22.18s22.25 9.32 22.25 22.18zm-9.74 0c0-7.98-5.79-13.44-12.51-13.44s-12.51 5.46-12.51 13.44c0 7.9 5.79 13.44 12.51 13.44s12.51-5.55 12.51-13.44z" fill="#FBBC05"/>
                            <path d="M209.75 26.34v39.82c0 16.38-9.66 23.07-21.08 23.07-10.75 0-17.22-7.19-19.66-13.07l8.48-3.53c1.51 3.61 5.21 7.87 11.17 7.87 7.31 0 11.84-4.51 11.84-13v-3.19h-.34c-2.18 2.69-6.38 5.04-11.68 5.04-11.09 0-21.25-9.66-21.25-22.09 0-12.52 10.16-22.26 21.25-22.26 5.29 0 9.49 2.35 11.68 4.96h.34v-3.61h9.25zm-8.56 20.92c0-7.81-5.21-13.52-11.84-13.52-6.72 0-12.35 5.71-12.35 13.52 0 7.73 5.63 13.36 12.35 13.36 6.63 0 11.84-5.63 11.84-13.36z" fill="#34A853"/>
                            <path d="M225 3v65h-9.5V3h9.5z" fill="#EA4335"/>
                            <path d="M262.02 54.48l7.56 5.04c-2.44 3.61-8.32 9.83-18.48 9.83-12.6 0-22.01-9.74-22.01-22.18 0-13.19 9.49-22.18 20.92-22.18 11.51 0 17.14 9.16 18.98 14.11l1.01 2.52-29.65 12.28c2.27 4.45 5.8 6.72 10.75 6.72 4.96 0 8.4-2.44 10.92-6.14zm-23.27-7.98l19.82-8.23c-1.09-2.77-4.37-4.7-8.23-4.7-4.95 0-11.84 4.37-11.59 12.93z" fill="#FBBC05"/>
                            <path d="M35.29 41.41V32H67c.31 1.64.47 3.58.47 5.68 0 7.06-1.93 15.79-8.15 22.01-6.05 6.3-13.78 9.66-24.02 9.66C16.32 69.35.36 53.89.36 34.91.36 15.93 16.32.47 35.3.47c10.5 0 17.98 4.12 23.6 9.49l-6.64 6.64c-4.03-3.78-9.49-6.72-16.97-6.72-13.86 0-24.7 11.17-24.7 25.03 0 13.86 10.84 25.03 24.7 25.03 8.99 0 14.11-3.61 17.39-6.89 2.66-2.66 4.41-6.46 5.1-11.65l-22.49.01z" fill="#EA4335"/>
                        </g>
                    </svg>
                </div>
                <h3>Google</h3>
                <p>Leading search engine and cloud services company</p>
            </div>
            <div class="company-card">
                <div class="company-logo" style="background: white; padding: 1rem;">
                    <svg width="60" height="18" viewBox="0 0 603 182" xmlns="http://www.w3.org/2000/svg">
                        <g fill="#FF9900" fill-rule="nonzero">
                            <path d="M374.456 72.864l-12.696 37.944h-8.712L340.2 72.864h8.712l9.504 31.032 9.504-31.032h8.536zm-53.928 0v37.944h-7.92V72.864h7.92zm-20.592 0l-12.696 37.944h-8.712L265.68 72.864h8.712l9.504 31.032 9.504-31.032h8.536zm-53.928 0v37.944h-7.92V72.864h7.92zm-20.592 0l-12.696 37.944h-8.712L191.16 72.864h8.712l9.504 31.032 9.504-31.032h8.536zm-53.928 0v37.944h-7.92V72.864h7.92zm-20.592 0l-12.696 37.944h-8.712L116.64 72.864h8.712l9.504 31.032 9.504-31.032h8.536zm-53.928 0v37.944h-7.92V72.864h7.92zm-20.592 0l-12.696 37.944H42.12L29.424 72.864h8.712l9.504 31.032 9.504-31.032h8.536z"/>
                            <path d="M566.28 72.864c11.88 0 21.384 9.504 21.384 21.384s-9.504 21.384-21.384 21.384h-21.384V72.864h21.384zm0 34.848c7.128 0 12.936-5.808 12.936-12.936s-5.808-12.936-12.936-12.936h-12.936v25.872h12.936z"/>
                        </g>
                    </svg>
                </div>
                <h3>Amazon</h3>
                <p>Global e-commerce and cloud computing leader</p>
            </div>
            <div class="company-card">
                <div class="company-logo" style="background: white; padding: 1rem;">
                    <svg width="60" height="13" viewBox="0 0 609 130" xmlns="http://www.w3.org/2000/svg">
                        <path d="M0 0h609v130H0z" fill="#00BCF2"/>
                        <path d="M24 24h561v82H24z" fill="#FFF"/>
                        <path d="M48 48h513v34H48z" fill="#00BCF2"/>
                        <text x="304" y="70" text-anchor="middle" fill="#FFF" font-family="Arial, sans-serif" font-size="24" font-weight="bold">Microsoft</text>
                    </svg>
                </div>
                <h3>Microsoft</h3>
                <p>Technology corporation and software developer</p>
            </div>
            <div class="company-card">
                <div class="company-logo" style="background: white; padding: 1rem;">
                    <svg width="60" height="20" viewBox="0 0 200 60" xmlns="http://www.w3.org/2000/svg">
                        <rect width="200" height="60" fill="#0077B5"/>
                        <text x="100" y="35" text-anchor="middle" fill="#FFF" font-family="Arial, sans-serif" font-size="16" font-weight="bold">Infosys</text>
                    </svg>
                </div>
                <h3>Infosys</h3>
                <p>Global leader in consulting and IT services</p>
            </div>
            <div class="company-card">
                <div class="company-logo" style="background: white; padding: 1rem;">
                    <svg width="60" height="20" viewBox="0 0 200 60" xmlns="http://www.w3.org/2000/svg">
                        <rect width="200" height="60" fill="#1BA1E2"/>
                        <text x="100" y="35" text-anchor="middle" fill="#FFF" font-family="Arial, sans-serif" font-size="20" font-weight="bold">TCS</text>
                    </svg>
                </div>
                <h3>TCS</h3>
                <p>Multinational IT services and consulting company</p>
            </div>
            <div class="company-card">
                <div class="company-logo" style="background: white; padding: 1rem;">
                    <svg width="60" height="20" viewBox="0 0 200 60" xmlns="http://www.w3.org/2000/svg">
                        <rect width="200" height="60" fill="#A100FF"/>
                        <text x="100" y="35" text-anchor="middle" fill="#FFF" font-family="Arial, sans-serif" font-size="14" font-weight="bold">Accenture</text>
                    </svg>
                </div>
                <h3>Accenture</h3>
                <p>Professional services company with leading capabilities</p>
            </div>
            <div class="company-card">
                <div class="company-logo" style="background: white; padding: 1rem;">
                    <svg width="60" height="20" viewBox="0 0 200 60" xmlns="http://www.w3.org/2000/svg">
                        <rect width="200" height="60" fill="#0066CC"/>
                        <text x="100" y="35" text-anchor="middle" fill="#FFF" font-family="Arial, sans-serif" font-size="16" font-weight="bold">Wipro</text>
                    </svg>
                </div>
                <h3>Wipro</h3>
                <p>Leading global information technology company</p>
            </div>
            <div class="company-card">
                <div class="company-logo" style="background: white; padding: 1rem;">
                    <svg width="60" height="20" viewBox="0 0 200 60" xmlns="http://www.w3.org/2000/svg">
                        <rect width="200" height="60" fill="#1F70C1"/>
                        <text x="100" y="35" text-anchor="middle" fill="#FFF" font-family="Arial, sans-serif" font-size="20" font-weight="bold">IBM</text>
                    </svg>
                </div>
                <h3>IBM</h3>
                <p>Multinational technology and consulting corporation</p>
            </div>
            <div class="company-card">
                <div class="company-logo" style="background: white; padding: 1rem;">
                    <svg width="60" height="20" viewBox="0 0 200 60" xmlns="http://www.w3.org/2000/svg">
                        <rect width="200" height="60" fill="#86BC25"/>
                        <text x="100" y="35" text-anchor="middle" fill="#FFF" font-family="Arial, sans-serif" font-size="14" font-weight="bold">Deloitte</text>
                    </svg>
                </div>
                <h3>Deloitte</h3>
                <p>Global professional services network</p>
            </div>
        </div>
    </div>
</section>

<!-- Running Counters Section -->
<section class="stats-section">
    <div class="container">
        <div class="stats-grid">
            <div class="stat-item">
                <span class="stat-number" data-target="<?php echo $stats['total_learners']; ?>">0</span>
                <span class="stat-label">Total Learners</span>
            </div>
            <div class="stat-item">
                <span class="stat-number" data-target="<?php echo $stats['students_placed']; ?>">0</span>
                <span class="stat-label">Students Placed</span>
            </div>
            <div class="stat-item">
                <span class="stat-number" data-target="<?php echo $stats['courses_offered']; ?>">0</span>
                <span class="stat-label">Courses Offered</span>
            </div>
            <div class="stat-item">
                <span class="stat-number" data-target="<?php echo $stats['mock_interviews']; ?>">0</span>
                <span class="stat-label">Mock Interviews</span>
            </div>
        </div>
    </div>
</section>

<!-- Testimonials Section -->
<section class="section">
    <div class="container">
        <div class="section-title">
            <h2>What Our Students Say</h2>
            <p>Real success stories from students who transformed their careers with InterviewPrep</p>
        </div>
        <div class="testimonials-grid">
            <div class="testimonial-card">
                <div class="testimonial-content">
                    <p>"InterviewPrep completely transformed my approach to technical interviews. The mock interviews were incredibly realistic and helped me identify my weak areas. I landed my dream job at Google within 3 months!"</p>
                </div>
                <div class="testimonial-author">
                    <div class="author-avatar">SA</div>
                    <div class="author-info">
                        <h4>Sarah Anderson</h4>
                        <p>Software Engineer at Google</p>
                    </div>
                </div>
            </div>
            <div class="testimonial-card">
                <div class="testimonial-content">
                    <p>"The DSA course was exceptional! The instructors explained complex algorithms in such a simple way. The practice problems were exactly what I encountered in my Amazon interview. Highly recommended!"</p>
                </div>
                <div class="testimonial-author">
                    <div class="author-avatar">RK</div>
                    <div class="author-info">
                        <h4>Raj Kumar</h4>
                        <p>Senior Developer at Amazon</p>
                    </div>
                </div>
            </div>
            <div class="testimonial-card">
                <div class="testimonial-content">
                    <p>"The personalized feedback and one-on-one mentoring sessions were game-changers. My confidence level increased dramatically, and I aced my Microsoft interview. Thank you, InterviewPrep!"</p>
                </div>
                <div class="testimonial-author">
                    <div class="author-avatar">EP</div>
                    <div class="author-info">
                        <h4>Emily Parker</h4>
                        <p>Product Manager at Microsoft</p>
                    </div>
                </div>
            </div>
            <div class="testimonial-card">
                <div class="testimonial-content">
                    <p>"From a complete beginner to landing a job at TCS, InterviewPrep guided me every step of the way. The comprehensive curriculum and supportive community made all the difference."</p>
                </div>
                <div class="testimonial-author">
                    <div class="author-avatar">AS</div>
                    <div class="author-info">
                        <h4>Arjun Singh</h4>
                        <p>Software Analyst at TCS</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Courses Highlight Section -->
<section class="section bg-secondary">
    <div class="container">
        <div class="section-title">
            <h2>Featured Courses</h2>
            <p>Comprehensive courses designed by industry experts to prepare you for success</p>
        </div>
        <div class="courses-grid">
            <div class="course-card">
                <div class="course-image">
                    <i class="fab fa-java"></i>
                </div>
                <div class="course-content">
                    <h3>Java Programming Mastery</h3>
                    <p>Complete Java programming course covering OOP concepts, collections, multithreading, and advanced topics essential for technical interviews.</p>
                    <div class="course-meta">
                        <span class="course-duration">
                            <i class="fas fa-clock"></i> 8 weeks
                        </span>
                        <span class="course-level">
                            <i class="fas fa-signal"></i> Intermediate
                        </span>
                    </div>
                    <a href="courses.php" class="btn btn-primary">Learn More</a>
                </div>
            </div>
            <div class="course-card">
                <div class="course-image">
                    <i class="fab fa-python"></i>
                </div>
                <div class="course-content">
                    <h3>Python for Interviews</h3>
                    <p>Master Python programming with focus on data structures, algorithms, and problem-solving techniques commonly asked in technical interviews.</p>
                    <div class="course-meta">
                        <span class="course-duration">
                            <i class="fas fa-clock"></i> 6 weeks
                        </span>
                        <span class="course-level">
                            <i class="fas fa-signal"></i> Beginner
                        </span>
                    </div>
                    <a href="courses.php" class="btn btn-primary">Learn More</a>
                </div>
            </div>
            <div class="course-card">
                <div class="course-image">
                    <i class="fas fa-project-diagram"></i>
                </div>
                <div class="course-content">
                    <h3>Data Structures & Algorithms</h3>
                    <p>Comprehensive DSA course covering arrays, linked lists, trees, graphs, sorting, searching, and dynamic programming with interview problems.</p>
                    <div class="course-meta">
                        <span class="course-duration">
                            <i class="fas fa-clock"></i> 12 weeks
                        </span>
                        <span class="course-level">
                            <i class="fas fa-signal"></i> Advanced
                        </span>
                    </div>
                    <a href="courses.php" class="btn btn-primary">Learn More</a>
                </div>
            </div>
            <div class="course-card">
                <div class="course-image">
                    <i class="fab fa-js-square"></i>
                </div>
                <div class="course-content">
                    <h3>JavaScript & Web Development</h3>
                    <p>Modern JavaScript programming including ES6+, DOM manipulation, async programming, and popular frameworks for web development interviews.</p>
                    <div class="course-meta">
                        <span class="course-duration">
                            <i class="fas fa-clock"></i> 10 weeks
                        </span>
                        <span class="course-level">
                            <i class="fas fa-signal"></i> Intermediate
                        </span>
                    </div>
                    <a href="courses.php" class="btn btn-primary">Learn More</a>
                </div>
            </div>
            <div class="course-card">
                <div class="course-image">
                    <i class="fas fa-database"></i>
                </div>
                <div class="course-content">
                    <h3>SQL & Database Design</h3>
                    <p>Master SQL queries, database design principles, normalization, indexing, and advanced topics for database-related technical interviews.</p>
                    <div class="course-meta">
                        <span class="course-duration">
                            <i class="fas fa-clock"></i> 4 weeks
                        </span>
                        <span class="course-level">
                            <i class="fas fa-signal"></i> Beginner
                        </span>
                    </div>
                    <a href="courses.php" class="btn btn-primary">Learn More</a>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Mock Interview Section -->
<section class="section">
    <div class="container">
        <div class="section-title">
            <h2>Mock Interview Platform</h2>
            <p>Practice with real interview scenarios and get personalized feedback from industry experts</p>
        </div>
        <div class="courses-grid">
            <div class="course-card">
                <div class="course-image" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);">
                    <i class="fas fa-video"></i>
                </div>
                <div class="course-content">
                    <h3>Live Mock Interviews</h3>
                    <p>One-on-one mock interviews with experienced interviewers from top tech companies. Get real-time feedback and improve your performance.</p>
                    <a href="mocks.php" class="btn btn-primary">Schedule Interview</a>
                </div>
            </div>
            <div class="course-card">
                <div class="course-image" style="background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);">
                    <i class="fas fa-code"></i>
                </div>
                <div class="course-content">
                    <h3>Coding Challenges</h3>
                    <p>Practice coding problems with our interactive platform. Solve problems similar to those asked in actual technical interviews.</p>
                    <a href="mocks.php" class="btn btn-primary">Start Coding</a>
                </div>
            </div>
            <div class="course-card">
                <div class="course-image" style="background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);">
                    <i class="fas fa-chart-line"></i>
                </div>
                <div class="course-content">
                    <h3>Performance Analytics</h3>
                    <p>Track your progress with detailed analytics. Identify strengths and weaknesses to focus your preparation effectively.</p>
                    <a href="mocks.php" class="btn btn-primary">View Analytics</a>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Dedicated IDE Section -->
<section class="section bg-secondary">
    <div class="container">
        <div class="about-company">
            <div class="about-content animate-fade-in-left">
                <h2>Online Coding IDE</h2>
                <p>Practice coding with our powerful online IDE that supports multiple programming languages. No setup required - start coding immediately in your browser.</p>
                <div style="margin: 2rem 0;">
                    <h4 style="color: var(--primary-color); margin-bottom: 1rem;">Features:</h4>
                    <ul style="list-style: none; padding: 0;">
                        <li style="margin-bottom: 0.5rem;"><i class="fas fa-check" style="color: var(--accent-color); margin-right: 0.5rem;"></i> Multi-language support (Java, Python, C++, JavaScript)</li>
                        <li style="margin-bottom: 0.5rem;"><i class="fas fa-check" style="color: var(--accent-color); margin-right: 0.5rem;"></i> Real-time code execution and debugging</li>
                        <li style="margin-bottom: 0.5rem;"><i class="fas fa-check" style="color: var(--accent-color); margin-right: 0.5rem;"></i> Syntax highlighting and auto-completion</li>
                        <li style="margin-bottom: 0.5rem;"><i class="fas fa-check" style="color: var(--accent-color); margin-right: 0.5rem;"></i> Save and share your code solutions</li>
                        <li style="margin-bottom: 0.5rem;"><i class="fas fa-check" style="color: var(--accent-color); margin-right: 0.5rem;"></i> Interview-style problem templates</li>
                    </ul>
                </div>
                <a href="resources.php" class="btn btn-primary">Try IDE Now</a>
            </div>
            <div class="about-images animate-fade-in-right">
                <div class="about-image" style="grid-column: 1 / -1;">
                    <div style="height: 300px; background: linear-gradient(135deg, #1e1e1e 0%, #2d2d30 100%); display: flex; align-items: center; justify-content: center; color: #00ff00; font-family: 'Courier New', monospace; font-size: 1rem; padding: 2rem; border-radius: var(--radius-lg); position: relative; overflow: hidden;">
                        <div style="text-align: left; width: 100%;">
                            <div style="color: #569cd6;">public class</div>
                            <div style="color: #4ec9b0; margin-left: 1rem;">HelloWorld {</div>
                            <div style="color: #569cd6; margin-left: 2rem;">public static void</div>
                            <div style="color: #dcdcaa; margin-left: 3rem;">main(String[] args) {</div>
                            <div style="color: #ce9178; margin-left: 4rem;">System.out.println("Hello, InterviewPrep!");</div>
                            <div style="margin-left: 3rem;">}</div>
                            <div style="margin-left: 1rem;">}</div>
                            <div style="position: absolute; top: 10px; right: 15px; color: #007acc; font-size: 2rem;">
                                <i class="fas fa-terminal"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<?php require_once 'includes/footer.php'; ?>
